services:
  - type: web
    name: hii
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn hii.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - fromDatabase:
          name: hii-db
          property: connectionString
        sync: false

databases:
  - name: hii-db
    databaseName: hii
    user: hii
